<?php

function mespronos_group_theme() {
  $themes = [];
  $themes['group-list'] = array(
    'template' => 'group-list',
    'variables' => array(
      'groups' => [],
    ),
  );
  $themes['group-description'] = array(
    'template' => 'group-description',
    'variables' => [],
  );
  $themes['group-form-warning'] = array(
    'template' => 'group-form-warning',
    'variables' => [],
  );
  return $themes;
}