<?php

/**
 * @file
 * Contains mespronos.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\mespronos\Entity\Controller\BetController;

/**
 * Implements hook_help().
 */
function mespronos_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mespronos module.
    case 'help.page.mespronos':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Gestion de pronostics') . '</p>';
      return $output;

    default:
  }
}

function mespronos_game_update($entity) {
  BetController::updateBetsFromGame($entity);
}

/**
 * Implements hook_theme().
 */
function mespronos_theme() {
  $theme = [];

  return $theme;
}
