<?php

/**
 * @file
 * Contains mespronos.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\mespronos\Entity\Controller\BetController;

function mespronos_preprocess_page(&$variables) {
  if($variables['is_admin']) {
    $variables['#attached']['library'][] = 'mespronos/administration-style';
  }
  if($variables['is_front']) {
    $variables['#attached']['library'][] = 'mespronos/front-style';
  }
}

function mespronos_theme() {
  $theme = [];
  $theme['join'] = array(
    'variables' => array(
      'registration_form' => NULL,
    ),
  );

  return $theme;
}


/**
 * @todo create a proper page in \Drupal\mespronos\Controller\UserController
 */
function mespronos_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['account']['pass']['#description'] = null;
  $form['account']['mail']['#description'] = null;
  $form['account']['name']['#description'] = null;
  $form['status']['#access'] = false;
  $form['roles']['#access'] = false;
  $form['notify']['#access'] = false;
  $form['user_picture']['widget'][0]['#description'] = null;
  $form['contact']['#access'] = false;
}