<?php

/**
 * @file
 * Contains mespronos.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\mespronos\Entity\Controller\BetController;

function mespronos_preprocess_page(&$variables) {
  if($variables['is_admin']) {
    $variables['#attached']['library'][] = 'mespronos/administration-style';
  }
  if($variables['is_front']) {
    $variables['#attached']['library'][] = 'mespronos/front-style';
  }
}

function mespronos_theme() {
  $theme = [];
  $theme['join'] = array(
    'variables' => array(
      'login_form' => NULL,
      'registration_form' => NULL,
    ),
  );

  return $theme;
}
