<?php
function mespronos_sports_install() {
  $entities = [
    entity_create('sport', array(
      'created' => time(),
      'changed' => time(),
      'user_id' => 1,
      'name' => 'Football',
    )),
    entity_create('sport', array(
      'created' => time(),
      'changed' => time(),
      'user_id' => 1,
      'name' => 'Rugby',
    )),
  ];
  foreach ($entities as $entity) {
    $entity->save();
  }
}