<?php

/**
 * @file
 * Contains mespronos_teams.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mespronos_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mespronos_teams module.
    case 'help.page.mespronos':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Gestion de la configuration globale du site') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mespronos_theme() {
  $theme = [];

  return $theme;
}
