<?php

/**
 * @file
 * Contains mespronos_configuration.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mespronos_configuration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mespronos_configuration module.
    case 'help.page.mespronos_configuration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Advanced config for a full experience with MesPronos') . '</p>';
      return $output;

    default:
  }
}
